<?php 
	$this->inlineScript()->appendFile('/assets/moment/min/moment-with-locales.min.js');
	$this->inlineScript()->appendFile('/assets/holderjs/holder.js');
?>

<h1><?= $this->article->getTitle()?></h1>
<h4>Dans la catégorie <strong>
<?php 
$categorieArray[] = $this->article->getCategorie()->getNom(); 
$categorie = $this->article->getCategorie();
while($categorie->getParent() !== null) {
    $categorieArray[] = $categorie->getParent()->getNom();
    $categorie = $categorie->getParent();
}
$string = null;
foreach (array_reverse($categorieArray) as $cat) {
    $string .= $cat . ' >> ';
}
echo trim($string, ' >> ');
?>
</strong></h4>
<h4>Auteur :<?= $this->article->getAuthor()->getName();?></h4>
<p><?= $this->article->getContent()?></p>
<hr />
<div id="commentsList">

</div>
<hr />
<button id="addComment" class="btn btn-sm btn-default">Ajouter un commentaire</button>
<div id="commentForm" class="hidden">
	<p>&nbsp;</p>
	<p><textarea row="6" cols="60" id="comment" placeholder="votre commentaire"></textarea></p>
	<p><button id="sendComment" class="btn btn-sm btn-success">Publier</button></p>
</div>
<p>&nbsp;</p>
<script>
<?php $this->inlineScript()->captureStart()?>

function loadComments()
{
	$.get('/Core/article/readcomments/article/<?= $this->article->getId()?>', 
			function(data) {
				output = '<ul class="media-list">';
				moment.locale('fr');	
				$.each(data, function(index, comment) {
					time = moment(comment.comment_datetime);
					output = output + '<li class="media">';
					output = output + ' <a class="pull-left" href="#"><img class="media-object" src="holder.js/64x64" alt="..."></a>';
					output = output + '<div class="media-body"> <h4 class="media-heading">Par ' + comment.user_login + ' ';
					output = output + time.fromNow() + '</h4>';
					output = output + comment.comment_content + '<br />';
					output = output + '</div></li>';
				});
				output = output + '</ul>';
				$('#commentsList').html(output);
				Holder.run();
			}
	); 
}

$(document).ready(function(){

	$('#addComment').on('click', function(e){
		e.preventDefault();
		$('#commentForm').removeClass('hidden');
		$('#addComment').addClass('disabled');
	});

	$('#sendComment').on('click', function(e){
		$.post(
				'<?= $this->url(array(), 'coreArticleAddcomment')?>',
				{ 
				  comment: $('#comment').val(), 
				  article: <?= $this->article->getId()?>
				}
			  ).done(function(data) {
				loadComments();
				$('#commentForm').addClass('hidden');
				$('#addComment').removeClass('disabled');
				$('#comment').val('');
			  });
	});

	// PAGE INIT
	loadComments();
	
});
<?php $this->inlineScript()->captureEnd()?>
</script>

