<?php
$this->inlineScript()->appendFile('/assets/jquery-xml2json/src/xml2json.js');
$this->inlineScript()->appendFile('/assets/jquery.soap/jquery.soap.js');
?>




<div>Type de météo : <br />
<?php foreach($this->result as $result) :?>
<p>
<?= $result->Description ?> &nbsp; <img src="<?= $result->PictureURL?>" />
<?php endforeach;?>
</div>

<script>
<?php $this->inlineScript()->captureStart()?>
$(document).ready(function(){
	$.soap({
	    url: 'http://www.project.dev/ws#',
	    method: 'test',

	    data: {
	        testIn: 'Remy Blom'
	    },

	    success: function (soapResponse) {
		    console.log(soapResponse.toJSON());
	    },
	    error: function (SOAPResponse) {
	        // show error
	    }
	});
	
});
<?php $this->inlineScript()->captureEnd()?>
</script>
